# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scrollbar_v2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 645)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget_envs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_envs.setObjectName("tabWidget_envs")
        self.tab_env1 = QtWidgets.QWidget()
        self.tab_env1.setObjectName("tab_env1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_env1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.games_scrollArea = QtWidgets.QScrollArea(self.tab_env1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.games_scrollArea.sizePolicy().hasHeightForWidth())
        self.games_scrollArea.setSizePolicy(sizePolicy)
        self.games_scrollArea.setWidgetResizable(True)
        self.games_scrollArea.setObjectName("games_scrollArea")
        self.games_verticalLayout = QtWidgets.QWidget()
        self.games_verticalLayout.setGeometry(QtCore.QRect(0, 0, 536, 473))
        self.games_verticalLayout.setObjectName("games_verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.games_verticalLayout)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_game1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_game1.setObjectName("horizontalLayout_game1")
        self.label_2 = QtWidgets.QLabel(self.games_verticalLayout)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_game1.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.games_verticalLayout)
        self.label.setObjectName("label")
        self.horizontalLayout_game1.addWidget(self.label)
        self.pushButton_3 = QtWidgets.QPushButton(self.games_verticalLayout)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_game1.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.games_verticalLayout)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_game1.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_game1)
        self.horizontalLayout_game2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_game2.setObjectName("horizontalLayout_game2")
        self.label_4 = QtWidgets.QLabel(self.games_verticalLayout)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_game2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.games_verticalLayout)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_game2.addWidget(self.label_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.games_verticalLayout)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_game2.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.games_verticalLayout)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_game2.addWidget(self.pushButton_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_game2)
        self.games_scrollArea.setWidget(self.games_verticalLayout)
        self.horizontalLayout.addWidget(self.games_scrollArea)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.game_ranking_scrollArea = QtWidgets.QScrollArea(self.tab_env1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_ranking_scrollArea.sizePolicy().hasHeightForWidth())
        self.game_ranking_scrollArea.setSizePolicy(sizePolicy)
        self.game_ranking_scrollArea.setWidgetResizable(True)
        self.game_ranking_scrollArea.setObjectName("game_ranking_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 537, 475))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_8.setAutoDefault(False)
        self.pushButton_8.setDefault(False)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.pushButton_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_5.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_5.addWidget(self.pushButton_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.game_ranking_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.addWidget(self.game_ranking_scrollArea, 1, 1, 1, 1)
        self.game_list_title = QtWidgets.QLabel(self.tab_env1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.game_list_title.setFont(font)
        self.game_list_title.setObjectName("game_list_title")
        self.gridLayout_5.addWidget(self.game_list_title, 0, 0, 1, 1)
        self.new_game_pb = QtWidgets.QPushButton(self.tab_env1)
        self.new_game_pb.setObjectName("new_game_pb")
        self.gridLayout_5.addWidget(self.new_game_pb, 2, 0, 1, 1)
        self.game_ranking_title = QtWidgets.QLabel(self.tab_env1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.game_ranking_title.setFont(font)
        self.game_ranking_title.setObjectName("game_ranking_title")
        self.gridLayout_5.addWidget(self.game_ranking_title, 0, 1, 1, 1)
        self.train_pb = QtWidgets.QPushButton(self.tab_env1)
        self.train_pb.setObjectName("train_pb")
        self.gridLayout_5.addWidget(self.train_pb, 2, 1, 1, 1)
        self.tabWidget_envs.addTab(self.tab_env1, "")
        self.tab_env2 = QtWidgets.QWidget()
        self.tab_env2.setObjectName("tab_env2")
        self.tabWidget_envs.addTab(self.tab_env2, "")
        self.gridLayout_4.addWidget(self.tabWidget_envs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_envs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "->"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "->"))
        self.pushButton_7.setText(_translate("MainWindow", "<-"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_8.setText(_translate("MainWindow", "move up"))
        self.pushButton_9.setText(_translate("MainWindow", "move down"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.game_list_title.setText(_translate("MainWindow", "Game list"))
        self.new_game_pb.setText(_translate("MainWindow", "New game"))
        self.game_ranking_title.setText(_translate("MainWindow", "Game ranking"))
        self.train_pb.setText(_translate("MainWindow", "Train"))
        self.tabWidget_envs.setTabText(self.tabWidget_envs.indexOf(self.tab_env1), _translate("MainWindow", "Tab 1"))
        self.tabWidget_envs.setTabText(self.tabWidget_envs.indexOf(self.tab_env2), _translate("MainWindow", "Tab 2"))

